export const RISK_FLAGS = [
  "MINT_AUTHORITY_PRESENT",
  "MINT_AUTHORITY_DISABLED",
  "MINT_AUTHORITY_UNKNOWN",
  "FREEZE_AUTHORITY_PRESENT",
  "FREEZE_AUTHORITY_DISABLED",
  "FREEZE_AUTHORITY_UNKNOWN",
  "LOW_LIQUIDITY",
  "MEDIUM_LIQUIDITY",
  "MISSING_LIQUIDITY",
  "MISSING_PAIR",
  "PAIR_TOO_NEW",
  "PAIR_YOUNG",
  "HIGH_PRICE_IMPACT",
  "MEDIUM_PRICE_IMPACT",
  "MISSING_QUOTE",
  "MISSING_AUTHORITY_EVIDENCE",
] as const;

export type RiskFlag = (typeof RISK_FLAGS)[number];
