// Trusted migration history and exact SQLite schema, generated from reviewed migration SQL.
// Historical entries are immutable; append new versions after schema review.
export const migrationContract = [
  {
    file: "0000_tense_aqueduct.sql",
    when: 1782009665917,
    sha256: "fe092b6708bb4493994493c3fa5a3710f23c7a15134ed84cb29ad8add3b35831",
    legacyCrlfSha256: "df6d92b35ade2638fa902a48f19cfc07dd0d5edbf1c2c8b8188ac1387efd30c5",
    schema: [
      {
        type: "index",
        name: "idx_equity_snapshots_session_id",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_session_id` ON `equity_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_equity_snapshots_timestamp_ms",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_timestamp_ms` ON `equity_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_filled_at_ms",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_filled_at_ms` ON `fills` (`filled_at_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_order_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_order_id` ON `fills` (`order_id`)",
      },
      {
        type: "index",
        name: "idx_fills_session_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_session_id` ON `fills` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_created_at_ms",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_created_at_ms` ON `orders` (`created_at_ms`)",
      },
      {
        type: "index",
        name: "idx_orders_mint_address",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_mint_address` ON `orders` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_orders_session_id",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_session_id` ON `orders` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_side",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_side` ON `orders` (`side`)",
      },
      {
        type: "index",
        name: "idx_orders_status",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_status` ON `orders` (`status`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_position_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_position_id` ON `position_snapshots` (`position_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_session_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_session_id` ON `position_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_timestamp_ms",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_timestamp_ms` ON `position_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_mint_address",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_mint_address` ON `positions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_positions_opened_at_ms",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_opened_at_ms` ON `positions` (`opened_at_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_session_id",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_session_id` ON `positions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_positions_status",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_status` ON `positions` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_provider",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_provider` ON `provider_health` (`provider`)",
      },
      {
        type: "index",
        name: "idx_provider_health_session_id",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_session_id` ON `provider_health` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_provider_health_status",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_status` ON `provider_health` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_timestamp_ms",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_timestamp_ms` ON `provider_health` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_checked_at_ms",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_checked_at_ms` ON `risk_assessments` (`checked_at_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_mint_address",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_mint_address` ON `risk_assessments` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_result",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_result` ON `risk_assessments` (`result`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_session_id",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_session_id` ON `risk_assessments` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_sessions_mode",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_mode` ON `sessions` (`mode`)",
      },
      {
        type: "index",
        name: "idx_sessions_started_at_ms",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_started_at_ms` ON `sessions` (`started_at_ms`)",
      },
      {
        type: "index",
        name: "idx_sessions_status",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_status` ON `sessions` (`status`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decided_at_ms",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decided_at_ms` ON `strategy_decisions` (`decided_at_ms`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decision",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decision` ON `strategy_decisions` (`decision`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_mint_address",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_mint_address` ON `strategy_decisions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_session_id",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_session_id` ON `strategy_decisions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_level",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_level` ON `system_logs` (`level`)",
      },
      {
        type: "index",
        name: "idx_system_logs_scope",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_scope` ON `system_logs` (`scope`)",
      },
      {
        type: "index",
        name: "idx_system_logs_session_id",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_session_id` ON `system_logs` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_timestamp_ms",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_timestamp_ms` ON `system_logs` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_first_seen_at_ms",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_first_seen_at_ms` ON `token_radar` (`first_seen_at_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_mint_address",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_mint_address` ON `token_radar` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_token_radar_session_id",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_session_id` ON `token_radar` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_token_radar_status",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_status` ON `token_radar` (`status`)",
      },
      {
        type: "index",
        name: "uq_token_radar_session_mint_source_pair",
        tbl_name: "token_radar",
        sql: "CREATE UNIQUE INDEX `uq_token_radar_session_mint_source_pair` ON `token_radar` (`session_id`,`mint_address`,`source`,`pair_address`)",
      },
      {
        type: "table",
        name: "equity_snapshots",
        tbl_name: "equity_snapshots",
        sql: "CREATE TABLE `equity_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`cash_lamports` integer NOT NULL,\n\t`open_position_value_lamports` integer NOT NULL,\n\t`total_equity_lamports` integer NOT NULL,\n\t`realized_pnl_lamports` integer NOT NULL,\n\t`unrealized_pnl_lamports` integer NOT NULL,\n\t`drawdown_lamports` integer,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "fills",
        tbl_name: "fills",
        sql: "CREATE TABLE `fills` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`filled_at_ms` integer NOT NULL,\n\t`fill_price_sol` text,\n\t`fill_price_usd` text,\n\t`tokens_filled` text,\n\t`sol_spent_lamports` integer,\n\t`sol_received_lamports` integer,\n\t`estimated_base_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_priority_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_slippage_lamports` integer DEFAULT 0 NOT NULL,\n\t`price_impact_bps` integer,\n\t`quote_source` text,\n\t`raw_quote_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "orders",
        tbl_name: "orders",
        sql: "CREATE TABLE `orders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mode` text NOT NULL,\n\t`side` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT 'CREATED' NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\t`requested_sol_lamports` integer,\n\t`requested_token_amount` text,\n\t`quote_source` text,\n\t`quote_id` text,\n\t`strategy_decision_id` text,\n\t`reason` text,\n\t`raw_order_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`strategy_decision_id`) REFERENCES `strategy_decisions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "position_snapshots",
        tbl_name: "position_snapshots",
        sql: "CREATE TABLE `position_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`position_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`mark_price_sol` text,\n\t`sell_quote_lamports` integer,\n\t`unrealized_pnl_lamports` integer,\n\t`unrealized_pnl_bps` integer,\n\t`liquidity_usd` text,\n\t`raw_quote_json` text,\n\tFOREIGN KEY (`position_id`) REFERENCES `positions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "positions",
        tbl_name: "positions",
        sql: "CREATE TABLE `positions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT 'OPEN' NOT NULL,\n\t`opened_at_ms` integer NOT NULL,\n\t`closed_at_ms` integer,\n\t`avg_entry_price_sol` text,\n\t`avg_exit_price_sol` text,\n\t`tokens_held` text NOT NULL,\n\t`cost_basis_lamports` integer DEFAULT 0 NOT NULL,\n\t`proceeds_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_bps` integer,\n\t`fees_paid_lamports` integer DEFAULT 0 NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "provider_health",
        tbl_name: "provider_health",
        sql: "CREATE TABLE `provider_health` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`provider` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`latency_ms` integer,\n\t`rate_limited` integer DEFAULT false NOT NULL,\n\t`error_message` text,\n\t`credits_used` integer,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "risk_assessments",
        tbl_name: "risk_assessments",
        sql: "CREATE TABLE `risk_assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`token_radar_id` text,\n\t`mint_address` text NOT NULL,\n\t`checked_at_ms` integer NOT NULL,\n\t`score` integer,\n\t`result` text DEFAULT 'UNKNOWN' NOT NULL,\n\t`passed` integer DEFAULT false NOT NULL,\n\t`mint_authority_disabled` integer,\n\t`freeze_authority_disabled` integer,\n\t`token_program` text,\n\t`top_holders_percent` text,\n\t`liquidity_usd` text,\n\t`risk_flags_json` text NOT NULL,\n\t`raw_provider_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`token_radar_id`) REFERENCES `token_radar`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "sessions",
        tbl_name: "sessions",
        sql: "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`mode` text NOT NULL,\n\t`status` text DEFAULT 'CREATED' NOT NULL,\n\t`started_at_ms` integer NOT NULL,\n\t`ended_at_ms` integer,\n\t`starting_balance_lamports` integer NOT NULL,\n\t`current_cash_lamports` integer NOT NULL,\n\t`target_profit_lamports` integer,\n\t`target_profit_bps` integer,\n\t`max_drawdown_lamports` integer,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`unrealized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`termination_reason` text DEFAULT 'NOT_TERMINATED' NOT NULL,\n\t`config_snapshot_json` text NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL\n)",
      },
      {
        type: "table",
        name: "strategy_decisions",
        tbl_name: "strategy_decisions",
        sql: "CREATE TABLE `strategy_decisions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`decided_at_ms` integer NOT NULL,\n\t`decision` text NOT NULL,\n\t`strategy_name` text NOT NULL,\n\t`score` integer,\n\t`reason` text NOT NULL,\n\t`input_snapshot_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "system_logs",
        tbl_name: "system_logs",
        sql: "CREATE TABLE `system_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`timestamp_ms` integer NOT NULL,\n\t`level` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`message` text NOT NULL,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "token_radar",
        tbl_name: "token_radar",
        sql: "CREATE TABLE `token_radar` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`symbol` text,\n\t`name` text,\n\t`pair_address` text,\n\t`source` text NOT NULL,\n\t`first_seen_at_ms` integer NOT NULL,\n\t`discovered_at_ms` integer NOT NULL,\n\t`price_usd` text,\n\t`price_sol` text,\n\t`liquidity_usd` text,\n\t`volume_5m_usd` text,\n\t`volume_1h_usd` text,\n\t`age_seconds` integer,\n\t`status` text DEFAULT 'DISCOVERED' NOT NULL,\n\t`notes` text,\n\t`raw_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
    ],
  },
  {
    file: "0001_gifted_killmonger.sql",
    when: 1782180300004,
    sha256: "326ebaf2b134fc95bd94cbe957828ff16fbc56c4081d1238a8dd279563ed7062",
    legacyCrlfSha256: "06662e00e3b11dbf55cc8ba558bed4c8a3afa3716d1aa7a813b2e93873679bee",
    schema: [
      {
        type: "index",
        name: "idx_equity_snapshots_session_id",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_session_id` ON `equity_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_equity_snapshots_timestamp_ms",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_timestamp_ms` ON `equity_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_filled_at_ms",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_filled_at_ms` ON `fills` (`filled_at_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_order_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_order_id` ON `fills` (`order_id`)",
      },
      {
        type: "index",
        name: "idx_fills_session_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_session_id` ON `fills` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_created_at_ms",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_created_at_ms` ON `orders` (`created_at_ms`)",
      },
      {
        type: "index",
        name: "idx_orders_mint_address",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_mint_address` ON `orders` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_orders_session_id",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_session_id` ON `orders` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_side",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_side` ON `orders` (`side`)",
      },
      {
        type: "index",
        name: "idx_orders_status",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_status` ON `orders` (`status`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_position_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_position_id` ON `position_snapshots` (`position_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_session_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_session_id` ON `position_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_timestamp_ms",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_timestamp_ms` ON `position_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_mint_address",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_mint_address` ON `positions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_positions_opened_at_ms",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_opened_at_ms` ON `positions` (`opened_at_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_session_id",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_session_id` ON `positions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_positions_status",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_status` ON `positions` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_provider",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_provider` ON `provider_health` (`provider`)",
      },
      {
        type: "index",
        name: "idx_provider_health_session_id",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_session_id` ON `provider_health` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_provider_health_status",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_status` ON `provider_health` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_timestamp_ms",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_timestamp_ms` ON `provider_health` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_checked_at_ms",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_checked_at_ms` ON `risk_assessments` (`checked_at_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_mint_address",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_mint_address` ON `risk_assessments` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_result",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_result` ON `risk_assessments` (`result`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_session_id",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_session_id` ON `risk_assessments` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_sessions_mode",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_mode` ON `sessions` (`mode`)",
      },
      {
        type: "index",
        name: "idx_sessions_started_at_ms",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_started_at_ms` ON `sessions` (`started_at_ms`)",
      },
      {
        type: "index",
        name: "idx_sessions_status",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_status` ON `sessions` (`status`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decided_at_ms",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decided_at_ms` ON `strategy_decisions` (`decided_at_ms`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decision",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decision` ON `strategy_decisions` (`decision`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_mint_address",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_mint_address` ON `strategy_decisions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_session_id",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_session_id` ON `strategy_decisions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_level",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_level` ON `system_logs` (`level`)",
      },
      {
        type: "index",
        name: "idx_system_logs_scope",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_scope` ON `system_logs` (`scope`)",
      },
      {
        type: "index",
        name: "idx_system_logs_session_id",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_session_id` ON `system_logs` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_timestamp_ms",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_timestamp_ms` ON `system_logs` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_first_seen_at_ms",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_first_seen_at_ms` ON `token_radar` (`first_seen_at_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_mint_address",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_mint_address` ON `token_radar` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_token_radar_session_id",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_session_id` ON `token_radar` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_token_radar_status",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_status` ON `token_radar` (`status`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_due_at_ms",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_due_at_ms` ON `watchlist_return_observations` (`due_at_ms`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_horizon_minutes",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_horizon_minutes` ON `watchlist_return_observations` (`horizon_minutes`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_mint_address",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_mint_address` ON `watchlist_return_observations` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_session_id",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_session_id` ON `watchlist_return_observations` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_status",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_status` ON `watchlist_return_observations` (`status`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_strategy_decision_id",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_strategy_decision_id` ON `watchlist_return_observations` (`strategy_decision_id`)",
      },
      {
        type: "index",
        name: "uq_token_radar_session_mint_source_pair",
        tbl_name: "token_radar",
        sql: "CREATE UNIQUE INDEX `uq_token_radar_session_mint_source_pair` ON `token_radar` (`session_id`,`mint_address`,`source`,`pair_address`)",
      },
      {
        type: "index",
        name: "uq_watchlist_returns_decision_horizon",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE UNIQUE INDEX `uq_watchlist_returns_decision_horizon` ON `watchlist_return_observations` (`strategy_decision_id`,`horizon_minutes`)",
      },
      {
        type: "table",
        name: "equity_snapshots",
        tbl_name: "equity_snapshots",
        sql: "CREATE TABLE `equity_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`cash_lamports` integer NOT NULL,\n\t`open_position_value_lamports` integer NOT NULL,\n\t`total_equity_lamports` integer NOT NULL,\n\t`realized_pnl_lamports` integer NOT NULL,\n\t`unrealized_pnl_lamports` integer NOT NULL,\n\t`drawdown_lamports` integer,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "fills",
        tbl_name: "fills",
        sql: "CREATE TABLE `fills` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`filled_at_ms` integer NOT NULL,\n\t`fill_price_sol` text,\n\t`fill_price_usd` text,\n\t`tokens_filled` text,\n\t`sol_spent_lamports` integer,\n\t`sol_received_lamports` integer,\n\t`estimated_base_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_priority_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_slippage_lamports` integer DEFAULT 0 NOT NULL,\n\t`price_impact_bps` integer,\n\t`quote_source` text,\n\t`raw_quote_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "orders",
        tbl_name: "orders",
        sql: "CREATE TABLE `orders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mode` text NOT NULL,\n\t`side` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT 'CREATED' NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\t`requested_sol_lamports` integer,\n\t`requested_token_amount` text,\n\t`quote_source` text,\n\t`quote_id` text,\n\t`strategy_decision_id` text,\n\t`reason` text,\n\t`raw_order_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`strategy_decision_id`) REFERENCES `strategy_decisions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "position_snapshots",
        tbl_name: "position_snapshots",
        sql: "CREATE TABLE `position_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`position_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`mark_price_sol` text,\n\t`sell_quote_lamports` integer,\n\t`unrealized_pnl_lamports` integer,\n\t`unrealized_pnl_bps` integer,\n\t`liquidity_usd` text,\n\t`raw_quote_json` text,\n\tFOREIGN KEY (`position_id`) REFERENCES `positions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "positions",
        tbl_name: "positions",
        sql: "CREATE TABLE `positions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT 'OPEN' NOT NULL,\n\t`opened_at_ms` integer NOT NULL,\n\t`closed_at_ms` integer,\n\t`avg_entry_price_sol` text,\n\t`avg_exit_price_sol` text,\n\t`tokens_held` text NOT NULL,\n\t`cost_basis_lamports` integer DEFAULT 0 NOT NULL,\n\t`proceeds_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_bps` integer,\n\t`fees_paid_lamports` integer DEFAULT 0 NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "provider_health",
        tbl_name: "provider_health",
        sql: "CREATE TABLE `provider_health` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`provider` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`latency_ms` integer,\n\t`rate_limited` integer DEFAULT false NOT NULL,\n\t`error_message` text,\n\t`credits_used` integer,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "risk_assessments",
        tbl_name: "risk_assessments",
        sql: "CREATE TABLE `risk_assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`token_radar_id` text,\n\t`mint_address` text NOT NULL,\n\t`checked_at_ms` integer NOT NULL,\n\t`score` integer,\n\t`result` text DEFAULT 'UNKNOWN' NOT NULL,\n\t`passed` integer DEFAULT false NOT NULL,\n\t`mint_authority_disabled` integer,\n\t`freeze_authority_disabled` integer,\n\t`token_program` text,\n\t`top_holders_percent` text,\n\t`liquidity_usd` text,\n\t`risk_flags_json` text NOT NULL,\n\t`raw_provider_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`token_radar_id`) REFERENCES `token_radar`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "sessions",
        tbl_name: "sessions",
        sql: "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`mode` text NOT NULL,\n\t`status` text DEFAULT 'CREATED' NOT NULL,\n\t`started_at_ms` integer NOT NULL,\n\t`ended_at_ms` integer,\n\t`starting_balance_lamports` integer NOT NULL,\n\t`current_cash_lamports` integer NOT NULL,\n\t`target_profit_lamports` integer,\n\t`target_profit_bps` integer,\n\t`max_drawdown_lamports` integer,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`unrealized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`termination_reason` text DEFAULT 'NOT_TERMINATED' NOT NULL,\n\t`config_snapshot_json` text NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL\n)",
      },
      {
        type: "table",
        name: "strategy_decisions",
        tbl_name: "strategy_decisions",
        sql: "CREATE TABLE `strategy_decisions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`decided_at_ms` integer NOT NULL,\n\t`decision` text NOT NULL,\n\t`strategy_name` text NOT NULL,\n\t`score` integer,\n\t`reason` text NOT NULL,\n\t`input_snapshot_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "system_logs",
        tbl_name: "system_logs",
        sql: "CREATE TABLE `system_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`timestamp_ms` integer NOT NULL,\n\t`level` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`message` text NOT NULL,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "token_radar",
        tbl_name: "token_radar",
        sql: "CREATE TABLE `token_radar` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`symbol` text,\n\t`name` text,\n\t`pair_address` text,\n\t`source` text NOT NULL,\n\t`first_seen_at_ms` integer NOT NULL,\n\t`discovered_at_ms` integer NOT NULL,\n\t`price_usd` text,\n\t`price_sol` text,\n\t`liquidity_usd` text,\n\t`volume_5m_usd` text,\n\t`volume_1h_usd` text,\n\t`age_seconds` integer,\n\t`status` text DEFAULT 'DISCOVERED' NOT NULL,\n\t`notes` text,\n\t`raw_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "watchlist_return_observations",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE TABLE `watchlist_return_observations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`strategy_decision_id` text NOT NULL,\n\t`token_radar_id` text,\n\t`mint_address` text NOT NULL,\n\t`pair_address` text,\n\t`symbol` text,\n\t`decision` text NOT NULL,\n\t`strategy_name` text NOT NULL,\n\t`strategy_score` integer,\n\t`horizon_minutes` integer NOT NULL,\n\t`baseline_observed_at_ms` integer NOT NULL,\n\t`baseline_price_sol` text,\n\t`baseline_price_usd` text,\n\t`baseline_liquidity_usd` text,\n\t`baseline_volume_5m_usd` text,\n\t`baseline_volume_1h_usd` text,\n\t`baseline_source` text NOT NULL,\n\t`due_at_ms` integer NOT NULL,\n\t`observed_at_ms` integer,\n\t`observed_price_sol` text,\n\t`observed_price_usd` text,\n\t`observed_liquidity_usd` text,\n\t`observed_volume_5m_usd` text,\n\t`observed_volume_1h_usd` text,\n\t`observed_source` text,\n\t`return_pct_sol` text,\n\t`return_pct_usd` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`error_code` text,\n\t`error_message` text,\n\t`raw_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`strategy_decision_id`) REFERENCES `strategy_decisions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`token_radar_id`) REFERENCES `token_radar`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
    ],
  },
  {
    file: "0002_h2_accounting_integrity.sql",
    when: 1789063200000,
    sha256: "446fe59cb3459dd574b1321eea06775386f9c8551ec6fc3c0614e904904fbd8d",
    legacyCrlfSha256: "8eff15549afc6fe4337e1841a37f7996d3374eaa038f21d978a54daed4c68bb3",
    schema: [
      {
        type: "index",
        name: "h2_decisions_owner",
        tbl_name: "strategy_decisions",
        sql: "CREATE UNIQUE INDEX `h2_decisions_owner` ON `strategy_decisions` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_fills_operation",
        tbl_name: "fills",
        sql: "CREATE UNIQUE INDEX `h2_fills_operation` ON `fills` (`operation_id`)",
      },
      {
        type: "index",
        name: "h2_fills_owner",
        tbl_name: "fills",
        sql: "CREATE UNIQUE INDEX `h2_fills_owner` ON `fills` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_operations_fill",
        tbl_name: "paper_operations",
        sql: "CREATE UNIQUE INDEX `h2_operations_fill` ON `paper_operations` (`fill_id`)",
      },
      {
        type: "index",
        name: "h2_operations_order",
        tbl_name: "paper_operations",
        sql: "CREATE UNIQUE INDEX `h2_operations_order` ON `paper_operations` (`order_id`)",
      },
      {
        type: "index",
        name: "h2_operations_owner",
        tbl_name: "paper_operations",
        sql: "CREATE UNIQUE INDEX `h2_operations_owner` ON `paper_operations` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_orders_operation",
        tbl_name: "orders",
        sql: "CREATE UNIQUE INDEX `h2_orders_operation` ON `orders` (`operation_id`)",
      },
      {
        type: "index",
        name: "h2_orders_owner",
        tbl_name: "orders",
        sql: "CREATE UNIQUE INDEX `h2_orders_owner` ON `orders` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_positions_active_mint",
        tbl_name: "positions",
        sql: "CREATE UNIQUE INDEX `h2_positions_active_mint` ON `positions` (`session_id`,`mint_address`) WHERE \"positions\".\"status\" IN ('OPEN', 'CLOSING')",
      },
      {
        type: "index",
        name: "h2_positions_owner",
        tbl_name: "positions",
        sql: "CREATE UNIQUE INDEX `h2_positions_owner` ON `positions` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_radar_null_pair",
        tbl_name: "token_radar",
        sql: 'CREATE UNIQUE INDEX `h2_radar_null_pair` ON `token_radar` (`session_id`,`mint_address`,`source`) WHERE "token_radar"."pair_address" IS NULL',
      },
      {
        type: "index",
        name: "h2_radar_owner",
        tbl_name: "token_radar",
        sql: "CREATE UNIQUE INDEX `h2_radar_owner` ON `token_radar` (`id`,`session_id`)",
      },
      {
        type: "index",
        name: "h2_sessions_owner_mode",
        tbl_name: "sessions",
        sql: "CREATE UNIQUE INDEX `h2_sessions_owner_mode` ON `sessions` (`id`,`mode`)",
      },
      {
        type: "index",
        name: "idx_equity_snapshots_session_id",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_session_id` ON `equity_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_equity_snapshots_timestamp_ms",
        tbl_name: "equity_snapshots",
        sql: "CREATE INDEX `idx_equity_snapshots_timestamp_ms` ON `equity_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_filled_at_ms",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_filled_at_ms` ON `fills` (`filled_at_ms`)",
      },
      {
        type: "index",
        name: "idx_fills_order_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_order_id` ON `fills` (`order_id`)",
      },
      {
        type: "index",
        name: "idx_fills_session_id",
        tbl_name: "fills",
        sql: "CREATE INDEX `idx_fills_session_id` ON `fills` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_created_at_ms",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_created_at_ms` ON `orders` (`created_at_ms`)",
      },
      {
        type: "index",
        name: "idx_orders_mint_address",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_mint_address` ON `orders` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_orders_session_id",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_session_id` ON `orders` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_orders_side",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_side` ON `orders` (`side`)",
      },
      {
        type: "index",
        name: "idx_orders_status",
        tbl_name: "orders",
        sql: "CREATE INDEX `idx_orders_status` ON `orders` (`status`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_position_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_position_id` ON `position_snapshots` (`position_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_session_id",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_session_id` ON `position_snapshots` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_position_snapshots_timestamp_ms",
        tbl_name: "position_snapshots",
        sql: "CREATE INDEX `idx_position_snapshots_timestamp_ms` ON `position_snapshots` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_mint_address",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_mint_address` ON `positions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_positions_opened_at_ms",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_opened_at_ms` ON `positions` (`opened_at_ms`)",
      },
      {
        type: "index",
        name: "idx_positions_session_id",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_session_id` ON `positions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_positions_status",
        tbl_name: "positions",
        sql: "CREATE INDEX `idx_positions_status` ON `positions` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_provider",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_provider` ON `provider_health` (`provider`)",
      },
      {
        type: "index",
        name: "idx_provider_health_session_id",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_session_id` ON `provider_health` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_provider_health_status",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_status` ON `provider_health` (`status`)",
      },
      {
        type: "index",
        name: "idx_provider_health_timestamp_ms",
        tbl_name: "provider_health",
        sql: "CREATE INDEX `idx_provider_health_timestamp_ms` ON `provider_health` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_checked_at_ms",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_checked_at_ms` ON `risk_assessments` (`checked_at_ms`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_mint_address",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_mint_address` ON `risk_assessments` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_result",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_result` ON `risk_assessments` (`result`)",
      },
      {
        type: "index",
        name: "idx_risk_assessments_session_id",
        tbl_name: "risk_assessments",
        sql: "CREATE INDEX `idx_risk_assessments_session_id` ON `risk_assessments` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_sessions_mode",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_mode` ON `sessions` (`mode`)",
      },
      {
        type: "index",
        name: "idx_sessions_started_at_ms",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_started_at_ms` ON `sessions` (`started_at_ms`)",
      },
      {
        type: "index",
        name: "idx_sessions_status",
        tbl_name: "sessions",
        sql: "CREATE INDEX `idx_sessions_status` ON `sessions` (`status`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decided_at_ms",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decided_at_ms` ON `strategy_decisions` (`decided_at_ms`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_decision",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_decision` ON `strategy_decisions` (`decision`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_mint_address",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_mint_address` ON `strategy_decisions` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_strategy_decisions_session_id",
        tbl_name: "strategy_decisions",
        sql: "CREATE INDEX `idx_strategy_decisions_session_id` ON `strategy_decisions` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_level",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_level` ON `system_logs` (`level`)",
      },
      {
        type: "index",
        name: "idx_system_logs_scope",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_scope` ON `system_logs` (`scope`)",
      },
      {
        type: "index",
        name: "idx_system_logs_session_id",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_session_id` ON `system_logs` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_system_logs_timestamp_ms",
        tbl_name: "system_logs",
        sql: "CREATE INDEX `idx_system_logs_timestamp_ms` ON `system_logs` (`timestamp_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_first_seen_at_ms",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_first_seen_at_ms` ON `token_radar` (`first_seen_at_ms`)",
      },
      {
        type: "index",
        name: "idx_token_radar_mint_address",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_mint_address` ON `token_radar` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_token_radar_session_id",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_session_id` ON `token_radar` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_token_radar_status",
        tbl_name: "token_radar",
        sql: "CREATE INDEX `idx_token_radar_status` ON `token_radar` (`status`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_due_at_ms",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_due_at_ms` ON `watchlist_return_observations` (`due_at_ms`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_horizon_minutes",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_horizon_minutes` ON `watchlist_return_observations` (`horizon_minutes`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_mint_address",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_mint_address` ON `watchlist_return_observations` (`mint_address`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_session_id",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_session_id` ON `watchlist_return_observations` (`session_id`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_status",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_status` ON `watchlist_return_observations` (`status`)",
      },
      {
        type: "index",
        name: "idx_watchlist_returns_strategy_decision_id",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE INDEX `idx_watchlist_returns_strategy_decision_id` ON `watchlist_return_observations` (`strategy_decision_id`)",
      },
      {
        type: "index",
        name: "uq_token_radar_session_mint_source_pair",
        tbl_name: "token_radar",
        sql: "CREATE UNIQUE INDEX `uq_token_radar_session_mint_source_pair` ON `token_radar` (`session_id`,`mint_address`,`source`,`pair_address`)",
      },
      {
        type: "index",
        name: "uq_watchlist_returns_decision_horizon",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE UNIQUE INDEX `uq_watchlist_returns_decision_horizon` ON `watchlist_return_observations` (`strategy_decision_id`,`horizon_minutes`)",
      },
      {
        type: "table",
        name: "equity_snapshots",
        tbl_name: "equity_snapshots",
        sql: "CREATE TABLE `equity_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`cash_lamports` integer NOT NULL,\n\t`open_position_value_lamports` integer NOT NULL,\n\t`total_equity_lamports` integer NOT NULL,\n\t`realized_pnl_lamports` integer NOT NULL,\n\t`unrealized_pnl_lamports` integer NOT NULL,\n\t`drawdown_lamports` integer,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "fills",
        tbl_name: "fills",
        sql: 'CREATE TABLE "fills" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`filled_at_ms` integer NOT NULL,\n\t`fill_price_sol` text,\n\t`fill_price_usd` text,\n\t`tokens_filled` text,\n\t`sol_spent_lamports` integer,\n\t`sol_received_lamports` integer,\n\t`estimated_base_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_priority_fee_lamports` integer DEFAULT 0 NOT NULL,\n\t`estimated_slippage_lamports` integer DEFAULT 0 NOT NULL,\n\t`price_impact_bps` integer,\n\t`quote_source` text,\n\t`raw_quote_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`operation_id` text,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`operation_id`) REFERENCES `paper_operations`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`order_id`,`session_id`) REFERENCES `orders`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`operation_id`,`session_id`) REFERENCES `paper_operations`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT "h2_fills_filled_at_ms" CHECK("fills"."filled_at_ms" IS NULL OR (typeof("fills"."filled_at_ms") = \'integer\' AND "fills"."filled_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_created_at_ms" CHECK("fills"."created_at_ms" IS NULL OR (typeof("fills"."created_at_ms") = \'integer\' AND "fills"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_sol_spent_lamports" CHECK("fills"."sol_spent_lamports" IS NULL OR (typeof("fills"."sol_spent_lamports") = \'integer\' AND "fills"."sol_spent_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_sol_received_lamports" CHECK("fills"."sol_received_lamports" IS NULL OR (typeof("fills"."sol_received_lamports") = \'integer\' AND "fills"."sol_received_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_estimated_base_fee_lamports" CHECK("fills"."estimated_base_fee_lamports" IS NULL OR (typeof("fills"."estimated_base_fee_lamports") = \'integer\' AND "fills"."estimated_base_fee_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_estimated_priority_fee_lamports" CHECK("fills"."estimated_priority_fee_lamports" IS NULL OR (typeof("fills"."estimated_priority_fee_lamports") = \'integer\' AND "fills"."estimated_priority_fee_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_estimated_slippage_lamports" CHECK("fills"."estimated_slippage_lamports" IS NULL OR (typeof("fills"."estimated_slippage_lamports") = \'integer\' AND "fills"."estimated_slippage_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_fills_price_impact_bps" CHECK("fills"."price_impact_bps" IS NULL OR (typeof("fills"."price_impact_bps") = \'integer\' AND "fills"."price_impact_bps" BETWEEN -9007199254740991 AND 9007199254740991))\n)',
      },
      {
        type: "table",
        name: "orders",
        tbl_name: "orders",
        sql: 'CREATE TABLE "orders" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mode` text NOT NULL,\n\t`side` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT \'CREATED\' NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\t`requested_sol_lamports` integer,\n\t`requested_token_amount` text,\n\t`quote_source` text,\n\t`quote_id` text,\n\t`strategy_decision_id` text,\n\t`reason` text,\n\t`raw_order_json` text,\n\t`operation_id` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`strategy_decision_id`) REFERENCES `strategy_decisions`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`operation_id`) REFERENCES `paper_operations`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`session_id`,`mode`) REFERENCES `sessions`(`id`,`mode`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`strategy_decision_id`,`session_id`) REFERENCES `strategy_decisions`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`operation_id`,`session_id`) REFERENCES `paper_operations`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT "h2_orders_mode" CHECK("orders"."mode" IN (\'PAPER\', \'LIVE\', \'BACKTEST\')),\n\tCONSTRAINT "h2_orders_side" CHECK("orders"."side" IN (\'BUY\', \'SELL\')),\n\tCONSTRAINT "h2_orders_status" CHECK("orders"."status" IN (\'CREATED\', \'QUOTED\', \'FILLED\', \'PARTIALLY_FILLED\', \'REJECTED\', \'FAILED\', \'CANCELLED\')),\n\tCONSTRAINT "h2_orders_created_at_ms" CHECK("orders"."created_at_ms" IS NULL OR (typeof("orders"."created_at_ms") = \'integer\' AND "orders"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_orders_updated_at_ms" CHECK("orders"."updated_at_ms" IS NULL OR (typeof("orders"."updated_at_ms") = \'integer\' AND "orders"."updated_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_orders_requested_sol_lamports" CHECK("orders"."requested_sol_lamports" IS NULL OR (typeof("orders"."requested_sol_lamports") = \'integer\' AND "orders"."requested_sol_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_orders_time_order" CHECK("orders"."updated_at_ms" >= "orders"."created_at_ms"),\n\tCONSTRAINT "h2_orders_operation_mode" CHECK("orders"."operation_id" IS NULL OR "orders"."mode" = \'PAPER\')\n)',
      },
      {
        type: "table",
        name: "paper_operations",
        tbl_name: "paper_operations",
        sql: 'CREATE TABLE `paper_operations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`version` integer NOT NULL,\n\t`mode` text DEFAULT \'PAPER\' NOT NULL,\n\t`session_id` text NOT NULL,\n\t`side` text NOT NULL,\n\t`source_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`strategy_decision_id` text,\n\t`input_position_id` text,\n\t`radar_id` text,\n\t`intent_digest` text NOT NULL,\n\t`intent_json` text NOT NULL,\n\t`state` text DEFAULT \'PENDING\' NOT NULL,\n\t`order_id` text,\n\t`fill_id` text,\n\t`result_position_id` text,\n\t`result_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`session_id`,`mode`) REFERENCES `sessions`(`id`,`mode`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`strategy_decision_id`,`session_id`) REFERENCES `strategy_decisions`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`input_position_id`,`session_id`) REFERENCES `positions`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`radar_id`,`session_id`) REFERENCES `token_radar`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`order_id`,`session_id`) REFERENCES `orders`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`fill_id`,`session_id`) REFERENCES `fills`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`result_position_id`,`session_id`) REFERENCES `positions`(`id`,`session_id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT "h2_operations_mode" CHECK("paper_operations"."mode" = \'PAPER\'),\n\tCONSTRAINT "h2_operations_side" CHECK("paper_operations"."side" IN (\'BUY\', \'SELL\')),\n\tCONSTRAINT "h2_operations_state" CHECK("paper_operations"."state" IN (\'PENDING\', \'COMMITTED\', \'REJECTED\')),\n\tCONSTRAINT "h2_operations_version" CHECK("paper_operations"."version" = 1),\n\tCONSTRAINT "h2_operations_digest" CHECK(length("paper_operations"."intent_digest") = 64 AND "paper_operations"."intent_digest" NOT GLOB \'*[^0-9a-f]*\'),\n\tCONSTRAINT "h2_operations_intent_json" CHECK(json_valid("paper_operations"."intent_json") AND json_type("paper_operations"."intent_json") = \'object\'),\n\tCONSTRAINT "h2_operations_source" CHECK(("paper_operations"."side" = \'BUY\' AND "paper_operations"."strategy_decision_id" IS NOT NULL AND "paper_operations"."source_id" = "paper_operations"."strategy_decision_id" AND "paper_operations"."radar_id" IS NOT NULL AND "paper_operations"."input_position_id" IS NULL) OR ("paper_operations"."side" = \'SELL\' AND "paper_operations"."input_position_id" IS NOT NULL AND "paper_operations"."source_id" = "paper_operations"."input_position_id" AND "paper_operations"."strategy_decision_id" IS NULL)),\n\tCONSTRAINT "h2_operations_result" CHECK(("paper_operations"."state" = \'PENDING\' AND "paper_operations"."order_id" IS NULL AND "paper_operations"."fill_id" IS NULL AND "paper_operations"."result_position_id" IS NULL AND "paper_operations"."result_json" IS NULL) OR ("paper_operations"."state" = \'REJECTED\' AND "paper_operations"."order_id" IS NOT NULL AND "paper_operations"."fill_id" IS NULL AND "paper_operations"."result_position_id" IS NULL AND "paper_operations"."result_json" IS NOT NULL AND json_valid("paper_operations"."result_json") AND json_type("paper_operations"."result_json") = \'object\') OR ("paper_operations"."state" = \'COMMITTED\' AND "paper_operations"."order_id" IS NOT NULL AND "paper_operations"."fill_id" IS NOT NULL AND "paper_operations"."result_position_id" IS NOT NULL AND "paper_operations"."result_json" IS NOT NULL AND json_valid("paper_operations"."result_json") AND json_type("paper_operations"."result_json") = \'object\')),\n\tCONSTRAINT "h2_operations_created_at_ms" CHECK("paper_operations"."created_at_ms" IS NULL OR (typeof("paper_operations"."created_at_ms") = \'integer\' AND "paper_operations"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_operations_updated_at_ms" CHECK("paper_operations"."updated_at_ms" IS NULL OR (typeof("paper_operations"."updated_at_ms") = \'integer\' AND "paper_operations"."updated_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_operations_time_order" CHECK("paper_operations"."updated_at_ms" >= "paper_operations"."created_at_ms")\n)',
      },
      {
        type: "table",
        name: "position_snapshots",
        tbl_name: "position_snapshots",
        sql: "CREATE TABLE `position_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`position_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`mark_price_sol` text,\n\t`sell_quote_lamports` integer,\n\t`unrealized_pnl_lamports` integer,\n\t`unrealized_pnl_bps` integer,\n\t`liquidity_usd` text,\n\t`raw_quote_json` text,\n\tFOREIGN KEY (`position_id`) REFERENCES `positions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
      },
      {
        type: "table",
        name: "positions",
        tbl_name: "positions",
        sql: 'CREATE TABLE "positions" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`status` text DEFAULT \'OPEN\' NOT NULL,\n\t`opened_at_ms` integer NOT NULL,\n\t`closed_at_ms` integer,\n\t`avg_entry_price_sol` text,\n\t`avg_exit_price_sol` text,\n\t`tokens_held` text NOT NULL,\n\t`cost_basis_lamports` integer DEFAULT 0 NOT NULL,\n\t`proceeds_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`realized_pnl_bps` integer,\n\t`fees_paid_lamports` integer DEFAULT 0 NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT "h2_positions_status" CHECK("positions"."status" IN (\'OPEN\', \'CLOSING\', \'CLOSED\', \'ERROR\')),\n\tCONSTRAINT "h2_positions_opened_at_ms" CHECK("positions"."opened_at_ms" IS NULL OR (typeof("positions"."opened_at_ms") = \'integer\' AND "positions"."opened_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_closed_at_ms" CHECK("positions"."closed_at_ms" IS NULL OR (typeof("positions"."closed_at_ms") = \'integer\' AND "positions"."closed_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_created_at_ms" CHECK("positions"."created_at_ms" IS NULL OR (typeof("positions"."created_at_ms") = \'integer\' AND "positions"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_updated_at_ms" CHECK("positions"."updated_at_ms" IS NULL OR (typeof("positions"."updated_at_ms") = \'integer\' AND "positions"."updated_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_cost_basis_lamports" CHECK("positions"."cost_basis_lamports" IS NULL OR (typeof("positions"."cost_basis_lamports") = \'integer\' AND "positions"."cost_basis_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_proceeds_lamports" CHECK("positions"."proceeds_lamports" IS NULL OR (typeof("positions"."proceeds_lamports") = \'integer\' AND "positions"."proceeds_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_fees_paid_lamports" CHECK("positions"."fees_paid_lamports" IS NULL OR (typeof("positions"."fees_paid_lamports") = \'integer\' AND "positions"."fees_paid_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_realized_pnl_lamports" CHECK("positions"."realized_pnl_lamports" IS NULL OR (typeof("positions"."realized_pnl_lamports") = \'integer\' AND "positions"."realized_pnl_lamports" BETWEEN -9007199254740991 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_realized_pnl_bps" CHECK("positions"."realized_pnl_bps" IS NULL OR (typeof("positions"."realized_pnl_bps") = \'integer\' AND "positions"."realized_pnl_bps" BETWEEN -9007199254740991 AND 9007199254740991)),\n\tCONSTRAINT "h2_positions_time_order" CHECK("positions"."updated_at_ms" >= "positions"."created_at_ms" AND ("positions"."closed_at_ms" IS NULL OR "positions"."closed_at_ms" >= "positions"."opened_at_ms"))\n)',
      },
      {
        type: "table",
        name: "provider_health",
        tbl_name: "provider_health",
        sql: "CREATE TABLE `provider_health` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`provider` text NOT NULL,\n\t`timestamp_ms` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`latency_ms` integer,\n\t`rate_limited` integer DEFAULT false NOT NULL,\n\t`error_message` text,\n\t`credits_used` integer,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "risk_assessments",
        tbl_name: "risk_assessments",
        sql: "CREATE TABLE `risk_assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`token_radar_id` text,\n\t`mint_address` text NOT NULL,\n\t`checked_at_ms` integer NOT NULL,\n\t`score` integer,\n\t`result` text DEFAULT 'UNKNOWN' NOT NULL,\n\t`passed` integer DEFAULT false NOT NULL,\n\t`mint_authority_disabled` integer,\n\t`freeze_authority_disabled` integer,\n\t`token_program` text,\n\t`top_holders_percent` text,\n\t`liquidity_usd` text,\n\t`risk_flags_json` text NOT NULL,\n\t`raw_provider_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`token_radar_id`) REFERENCES `token_radar`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "sessions",
        tbl_name: "sessions",
        sql: 'CREATE TABLE "sessions" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`mode` text NOT NULL,\n\t`status` text DEFAULT \'CREATED\' NOT NULL,\n\t`started_at_ms` integer NOT NULL,\n\t`ended_at_ms` integer,\n\t`starting_balance_lamports` integer NOT NULL,\n\t`current_cash_lamports` integer NOT NULL,\n\t`target_profit_lamports` integer,\n\t`target_profit_bps` integer,\n\t`max_drawdown_lamports` integer,\n\t`realized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`unrealized_pnl_lamports` integer DEFAULT 0 NOT NULL,\n\t`termination_reason` text DEFAULT \'NOT_TERMINATED\' NOT NULL,\n\t`config_snapshot_json` text NOT NULL,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tCONSTRAINT "h2_sessions_mode" CHECK("sessions"."mode" IN (\'PAPER\', \'LIVE\', \'BACKTEST\')),\n\tCONSTRAINT "h2_sessions_status" CHECK("sessions"."status" IN (\'CREATED\', \'RUNNING\', \'PAUSED\', \'COMPLETED\', \'FAILED\', \'CANCELLED\')),\n\tCONSTRAINT "h2_sessions_termination" CHECK("sessions"."termination_reason" IN (\'TARGET_REACHED\', \'MAX_DRAWDOWN\', \'DURATION_EXPIRED\', \'USER_STOP\', \'ENGINE_ERROR\', \'NOT_TERMINATED\')),\n\tCONSTRAINT "h2_sessions_started_at_ms" CHECK("sessions"."started_at_ms" IS NULL OR (typeof("sessions"."started_at_ms") = \'integer\' AND "sessions"."started_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_ended_at_ms" CHECK("sessions"."ended_at_ms" IS NULL OR (typeof("sessions"."ended_at_ms") = \'integer\' AND "sessions"."ended_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_created_at_ms" CHECK("sessions"."created_at_ms" IS NULL OR (typeof("sessions"."created_at_ms") = \'integer\' AND "sessions"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_updated_at_ms" CHECK("sessions"."updated_at_ms" IS NULL OR (typeof("sessions"."updated_at_ms") = \'integer\' AND "sessions"."updated_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_starting_balance_lamports" CHECK("sessions"."starting_balance_lamports" IS NULL OR (typeof("sessions"."starting_balance_lamports") = \'integer\' AND "sessions"."starting_balance_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_current_cash_lamports" CHECK("sessions"."current_cash_lamports" IS NULL OR (typeof("sessions"."current_cash_lamports") = \'integer\' AND "sessions"."current_cash_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_target_profit_lamports" CHECK("sessions"."target_profit_lamports" IS NULL OR (typeof("sessions"."target_profit_lamports") = \'integer\' AND "sessions"."target_profit_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_target_profit_bps" CHECK("sessions"."target_profit_bps" IS NULL OR (typeof("sessions"."target_profit_bps") = \'integer\' AND "sessions"."target_profit_bps" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_max_drawdown_lamports" CHECK("sessions"."max_drawdown_lamports" IS NULL OR (typeof("sessions"."max_drawdown_lamports") = \'integer\' AND "sessions"."max_drawdown_lamports" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_realized_pnl_lamports" CHECK("sessions"."realized_pnl_lamports" IS NULL OR (typeof("sessions"."realized_pnl_lamports") = \'integer\' AND "sessions"."realized_pnl_lamports" BETWEEN -9007199254740991 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_unrealized_pnl_lamports" CHECK("sessions"."unrealized_pnl_lamports" IS NULL OR (typeof("sessions"."unrealized_pnl_lamports") = \'integer\' AND "sessions"."unrealized_pnl_lamports" BETWEEN -9007199254740991 AND 9007199254740991)),\n\tCONSTRAINT "h2_sessions_time_order" CHECK("sessions"."updated_at_ms" >= "sessions"."created_at_ms" AND ("sessions"."ended_at_ms" IS NULL OR "sessions"."ended_at_ms" >= "sessions"."started_at_ms"))\n)',
      },
      {
        type: "table",
        name: "strategy_decisions",
        tbl_name: "strategy_decisions",
        sql: 'CREATE TABLE "strategy_decisions" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`decided_at_ms` integer NOT NULL,\n\t`decision` text NOT NULL,\n\t`strategy_name` text NOT NULL,\n\t`score` integer,\n\t`reason` text NOT NULL,\n\t`input_snapshot_json` text,\n\t`created_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT "h2_decisions_decision" CHECK("strategy_decisions"."decision" IN (\'WATCH\', \'SKIP\', \'BUY\', \'HOLD\', \'SELL\')),\n\tCONSTRAINT "h2_decisions_created_at_ms" CHECK("strategy_decisions"."created_at_ms" IS NULL OR (typeof("strategy_decisions"."created_at_ms") = \'integer\' AND "strategy_decisions"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_decisions_decided_at_ms" CHECK("strategy_decisions"."decided_at_ms" IS NULL OR (typeof("strategy_decisions"."decided_at_ms") = \'integer\' AND "strategy_decisions"."decided_at_ms" BETWEEN 0 AND 9007199254740991))\n)',
      },
      {
        type: "table",
        name: "system_logs",
        tbl_name: "system_logs",
        sql: "CREATE TABLE `system_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text,\n\t`timestamp_ms` integer NOT NULL,\n\t`level` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`message` text NOT NULL,\n\t`context_json` text,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "table",
        name: "token_radar",
        tbl_name: "token_radar",
        sql: 'CREATE TABLE "token_radar" (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`mint_address` text NOT NULL,\n\t`symbol` text,\n\t`name` text,\n\t`pair_address` text,\n\t`source` text NOT NULL,\n\t`first_seen_at_ms` integer NOT NULL,\n\t`discovered_at_ms` integer NOT NULL,\n\t`price_usd` text,\n\t`price_sol` text,\n\t`liquidity_usd` text,\n\t`volume_5m_usd` text,\n\t`volume_1h_usd` text,\n\t`age_seconds` integer,\n\t`status` text DEFAULT \'DISCOVERED\' NOT NULL,\n\t`notes` text,\n\t`raw_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT "h2_radar_status" CHECK("token_radar"."status" IN (\'DISCOVERED\', \'WATCHING\', \'REJECTED\', \'APPROVED\', \'BOUGHT\', \'IGNORED\', \'ERROR\')),\n\tCONSTRAINT "h2_radar_pair" CHECK("token_radar"."pair_address" IS NULL OR length(trim("token_radar"."pair_address")) > 0),\n\tCONSTRAINT "h2_radar_first_seen_at_ms" CHECK("token_radar"."first_seen_at_ms" IS NULL OR (typeof("token_radar"."first_seen_at_ms") = \'integer\' AND "token_radar"."first_seen_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_radar_discovered_at_ms" CHECK("token_radar"."discovered_at_ms" IS NULL OR (typeof("token_radar"."discovered_at_ms") = \'integer\' AND "token_radar"."discovered_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_radar_created_at_ms" CHECK("token_radar"."created_at_ms" IS NULL OR (typeof("token_radar"."created_at_ms") = \'integer\' AND "token_radar"."created_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_radar_updated_at_ms" CHECK("token_radar"."updated_at_ms" IS NULL OR (typeof("token_radar"."updated_at_ms") = \'integer\' AND "token_radar"."updated_at_ms" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_radar_age_seconds" CHECK("token_radar"."age_seconds" IS NULL OR (typeof("token_radar"."age_seconds") = \'integer\' AND "token_radar"."age_seconds" BETWEEN 0 AND 9007199254740991)),\n\tCONSTRAINT "h2_radar_time_order" CHECK("token_radar"."updated_at_ms" >= "token_radar"."created_at_ms")\n)',
      },
      {
        type: "table",
        name: "watchlist_return_observations",
        tbl_name: "watchlist_return_observations",
        sql: "CREATE TABLE `watchlist_return_observations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`strategy_decision_id` text NOT NULL,\n\t`token_radar_id` text,\n\t`mint_address` text NOT NULL,\n\t`pair_address` text,\n\t`symbol` text,\n\t`decision` text NOT NULL,\n\t`strategy_name` text NOT NULL,\n\t`strategy_score` integer,\n\t`horizon_minutes` integer NOT NULL,\n\t`baseline_observed_at_ms` integer NOT NULL,\n\t`baseline_price_sol` text,\n\t`baseline_price_usd` text,\n\t`baseline_liquidity_usd` text,\n\t`baseline_volume_5m_usd` text,\n\t`baseline_volume_1h_usd` text,\n\t`baseline_source` text NOT NULL,\n\t`due_at_ms` integer NOT NULL,\n\t`observed_at_ms` integer,\n\t`observed_price_sol` text,\n\t`observed_price_usd` text,\n\t`observed_liquidity_usd` text,\n\t`observed_volume_5m_usd` text,\n\t`observed_volume_1h_usd` text,\n\t`observed_source` text,\n\t`return_pct_sol` text,\n\t`return_pct_usd` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`error_code` text,\n\t`error_message` text,\n\t`raw_data_json` text,\n\t`created_at_ms` integer NOT NULL,\n\t`updated_at_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`strategy_decision_id`) REFERENCES `strategy_decisions`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`token_radar_id`) REFERENCES `token_radar`(`id`) ON UPDATE no action ON DELETE set null\n)",
      },
      {
        type: "trigger",
        name: "h2_operations_immutable_intent",
        tbl_name: "paper_operations",
        sql: "CREATE TRIGGER h2_operations_immutable_intent BEFORE UPDATE ON paper_operations\nWHEN NEW.id IS NOT OLD.id OR NEW.version IS NOT OLD.version OR NEW.mode IS NOT OLD.mode\n OR NEW.session_id IS NOT OLD.session_id OR NEW.side IS NOT OLD.side OR NEW.source_id IS NOT OLD.source_id\n OR NEW.mint_address IS NOT OLD.mint_address OR NEW.strategy_decision_id IS NOT OLD.strategy_decision_id\n OR NEW.input_position_id IS NOT OLD.input_position_id OR NEW.radar_id IS NOT OLD.radar_id\n OR NEW.intent_digest IS NOT OLD.intent_digest OR NEW.intent_json IS NOT OLD.intent_json\n OR NEW.created_at_ms IS NOT OLD.created_at_ms OR OLD.state != 'PENDING'\nBEGIN SELECT RAISE(ABORT, 'PAPER_OPERATION_IMMUTABLE'); END",
      },
      {
        type: "trigger",
        name: "h2_operations_no_delete",
        tbl_name: "paper_operations",
        sql: "CREATE TRIGGER h2_operations_no_delete BEFORE DELETE ON paper_operations\nBEGIN SELECT RAISE(ABORT, 'PAPER_OPERATION_IMMUTABLE'); END",
      },
    ],
  },
] as const;
